---
# Source: prowler/templates/api/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowler
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: prowler/templates/ui/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowler
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: prowler/templates/worker/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowler
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: prowler/templates/worker_beat/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prowler
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: prowler/templates/api/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prowler-api
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prowler-api
---
# Source: prowler/templates/ui/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prowler-ui
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prowler-ui
---
# Source: prowler/templates/worker/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prowler-worker
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prowler-worker
---
# Source: prowler/templates/worker_beat/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prowler-worker_beat
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: prowler-worker_beat
---
# Source: prowler/templates/api/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-api
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-api
  template:
    metadata:
      labels:
        helm.sh/chart: prowler-0.0.1
        app.kubernetes.io/instance: prowler
        app.kubernetes.io/version: "5.4.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prowler-api
    spec:
      serviceAccountName: prowler
      containers:
        - name: api
          image: "prowlercloud/prowler-api:5.4.4"
          imagePullPolicy: IfNotPresent
          command:
            - /home/prowler/docker-entrypoint.sh
            - prod
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: prowler/templates/ui/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-ui
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-ui
  template:
    metadata:
      labels:
        helm.sh/chart: prowler-0.0.1
        app.kubernetes.io/instance: prowler
        app.kubernetes.io/version: "5.4.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prowler-ui
    spec:
      serviceAccountName: prowler
      containers:
        - name: ui
          image: "prowlercloud/prowler-ui:5.4.4"
          imagePullPolicy: IfNotPresent
          command:
            - /home/prowler/docker-entrypoint.sh
            - prod
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: prowler/templates/worker/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-worker
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-worker
  template:
    metadata:
      labels:
        helm.sh/chart: prowler-0.0.1
        app.kubernetes.io/instance: prowler
        app.kubernetes.io/version: "5.4.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prowler-worker
    spec:
      serviceAccountName: prowler
      containers:
        - name: worker
          image: "prowlercloud/prowler-api:5.4.4"
          imagePullPolicy: IfNotPresent
          command:
            - /home/prowler/docker-entrypoint.sh
            - prod
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
---
# Source: prowler/templates/worker_beat/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowler-worker_beat
  labels:
    helm.sh/chart: prowler-0.0.1
    app.kubernetes.io/instance: prowler
    app.kubernetes.io/version: "5.4.4"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prowler-worker_beat
  template:
    metadata:
      labels:
        helm.sh/chart: prowler-0.0.1
        app.kubernetes.io/instance: prowler
        app.kubernetes.io/version: "5.4.4"
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/name: prowler-worker_beat
    spec:
      serviceAccountName: prowler
      containers:
        - name: worker_beat
          image: "prowlercloud/prowler-api:5.4.4"
          imagePullPolicy: IfNotPresent
          command:
            - /home/prowler/docker-entrypoint.sh
            - prod
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
