kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "prowler.fullname" . }}-ui
data:
  PROWLER_UI_VERSION: "stable"
  {{- if .Values.ui.ingress.enabled }}
  {{- with (first .Values.ui.ingress.hosts) }}
  AUTH_URL: "https://{{ .host }}"
  {{- end }}
  {{- else }}
  AUTH_URL: "http://localhost:{{ .Values.ui.service.port }}"
  {{- end }}
  API_BASE_URL: "http://{{ include "prowler.fullname" . }}-api:{{ .Values.api.service.port }}/api/v1"
  NEXT_PUBLIC_API_DOCS_URL: "http://{{ include "prowler.fullname" . }}-api:{{ .Values.api.service.port }}/api/v1/docs"
  AUTH_TRUST_HOST: "true"
  UI_PORT: {{ .Values.ui.service.port | quote }}
  # openssl rand -base64 32
  AUTH_SECRET: "N/c6mnaS5+SWq81+819OrzQZlmx1Vxtp/orjttJSmw8:"