kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "prowler.fullname" . }}-ui
data:
  PROWLER_UI_VERSION: "stable"
  {{- if .Values.ui.ingress.enabled }}
  {{- with (first .Values.ui.ingress.hosts) }}
  AUTH_URL: "https://{{ .host }}"
  {{- end }}
  {{- else if .Values.ui.gatewayAPI.httpRoute.enabled }}
  {{- with (first .Values.ui.gatewayAPI.httpRoute.hostnames) }}
  AUTH_URL: "https://{{ . }}"
  {{- else }}
  AUTH_URL: "http://localhost:{{ $.Values.ui.service.port }}"
  {{- end }}
  {{- else }}
  AUTH_URL: "http://localhost:{{ .Values.ui.service.port }}"
  {{- end }}
  API_BASE_URL: "http://{{ include "prowler.fullname" . }}-api:{{ .Values.api.service.port }}/api/v1"
  {{- if .Values.api.ingress.enabled }}
  {{- with (first .Values.api.ingress.hosts) }}
  NEXT_PUBLIC_API_BASE_URL: "https://{{ .host }}/api/v1"
  NEXT_PUBLIC_API_DOCS_URL: "https://{{ .host }}/api/v1/docs"
  {{- end }}
  {{- else }}
  NEXT_PUBLIC_API_BASE_URL: "http://{{ include "prowler.fullname" . }}-api:{{ .Values.api.service.port }}/api/v1"
  NEXT_PUBLIC_API_DOCS_URL: "http://{{ include "prowler.fullname" . }}-api:{{ .Values.api.service.port }}/api/v1/docs"
  {{- end }}
  AUTH_TRUST_HOST: "true"
  UI_PORT: {{ .Values.ui.service.port | quote }}