{{- if not .Values.ui.authSecret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowler.fullname" . }}-ui-auth
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
type: Opaque
stringData:
  # openssl rand -base64 32
  AUTH_SECRET: "N/c6mnaS5+SWq81+819OrzQZlmx1Vxtp/orjttJSmw8="
{{- end -}}
