{{- if .Values.postgresql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowler.fullname" . }}-api-postgres
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_HOST: "{{ include "prowler.fullname" . }}-postgresql"
  POSTGRES_PORT: "5432"
  # Existing user
  POSTGRES_ADMIN_USER: postgres
  POSTGRES_ADMIN_PASSWORD: postgres_password
  # User to be created
  POSTGRES_USER: prowler
  POSTGRES_PASSWORD: prowler_password
  # Existing DB
  POSTGRES_DB: prowler_db
{{- end -}}