{{- if .Values.neo4j.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowler.fullname" . }}-api-neo4j
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEO4J_HOST: "{{ include "prowler.fullname" . }}-neo4j"
  NEO4J_PORT: "7687"
  NEO4J_USER: "neo4j"
  NEO4J_PASSWORD: {{ .Values.neo4j.neo4j.password | quote }}
{{- end -}}
