{{- if .Values.valkey.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prowler.fullname" . }}-api-valkey
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
type: Opaque
stringData:
  VALKEY_HOST: "{{ include "prowler.fullname" . }}-valkey-headless"
  # VALKEY_PASSWORD: "valkey_password"
  VALKEY_PORT: "6379"
  VALKEY_DB: "0"
{{- end -}}