{{- if .Values.worker_beat.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "prowler.worker_beat.serviceAccountName" . }}
  labels:
    {{- include "prowler.labels" . | nindent 4 }}
  {{- with .Values.worker_beat.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.worker_beat.serviceAccount.automount }}
{{- end }}
